### ISSUE TITLE
additional_info dict not converted to string

### ISSUE THREAD

**Issue by jonasnic** [pwitab/sos-access#10]
```
response = client.send_alarm(
    event_code='AL',
    additional_info={'key': 'test'}
    )
```
> additional_info supports receiving a string, dict or an iterable (list, set, tuple). **If dict it will be generated as a string with all keys and values on different rows**. If an iterable it will be converted into a string with all items on different rows.

I tried sending an alarm similar to this. but at the receiving part (the alarm operator) say that they then don't receive the additional info line at all.

if I do this 
```
response = client.send_alarm(
    event_code='AL'
    )
```
they receive in their system 
additional_info=NAN

and doing this
```
response = client.send_alarm(
    event_code='AL',
    additional_info={'key = test'}
    )
```
will "work" in the sense that they receive the string "key = test"

so i believe that the dict to string conversion dont work

Windows
python 3.8

**Comment by Krolken** [comment]
Yeah. That was my bad. I fixed it and added tests for it.
Can you pull the branch and see if it fixes your problem.

**Comment by jonasnic** [comment]
it works :)

(its a bit troublesome to get files to the target computer, so i just found the missing `return text`  and added it to the local schemas.py)
