### ISSUE TITLE
tranmitter_time can't be string

### ISSUE THREAD

**Issue by jonasnic** [pwitab/sos-access#11]
send-alarm:
Parameters: 
event_code (str) – The event code of the alarm. 
**transmitter_time (str) – Time of the device or system sending the alarm** reference (str) – A reference that will show up in logs on the alarm receiver.

it gives error if the tranmitter_time is not a datetime but a string like '2020-03-03 12.30:32.12345'

> "'str' object has no attribute 'isoformat'"

**Comment by jonasnic** [comment]
![image](https://user-images.githubusercontent.com/19362689/75770331-04eeaa80-5d48-11ea-8add-93ce86f8d3ca.png)

**Comment by Krolken** [comment]
That is a documentation fault. It should be a datetime.

**Comment by jonasnic** [comment]
ok
