### ISSUE TITLE
pip install sos-access

### ISSUE THREAD

**Issue by jonasnic** [pwitab/sos-access#5]
when i try to install with PIP i get an error message.
ERROR: Could not find a version that satisfies the requirement SOS-access ( from version: none)
ERROR: no matching distribution found for sos-access

i have python 
-3.8-32
-3.7-64
-3.6-64
-3.5-64
-2.7-64
installed. all to PATH.
win10 machine

any idea what i could try to fix this?

**Comment by jonasnic** [comment]
now also tried with -3.6.0-64

**Comment by Krolken** [comment]
ok. I have not tried it on windows machines but can't see why it wouldn't work.
Are you using the global pip or have you created and activated a virtual environment?

**Comment by Krolken** [comment]
Also make sure you have the latest pip:

```
pip install pip --upgrade
```

**Comment by jonasnic** [comment]
just tested on my homecomputer.
here i have 3.5 and 3.7.
It gave errors and warning like instal latest pip. so when i worked my way thru that it instaled just fine.

but i noticed that `pip install pip --upgrade` did not effekt the PIP that python used (probably the global/cirtual environment thing you talked about)
so i did `py -m pip install --upgrade pip` and then i did py -m pip install sos-access...



now that i write this i realise i probably did this in cmd and not python on my work computer. that may be my error. will test later.

**Comment by jonasnic** [comment]
i now believe i was blocked behind my firms firewall or something.
i could not get it to work before changing my wifi

**Comment by Krolken** [comment]
OK. Since it seems to be an problem related to your network I'll close the issue and if you find other problems you can open a new one. Hope it works out for you.
