### ISSUE TITLE
marshmallow 3.4.0

### ISSUE THREAD

**Issue by jonasnic** [pwitab/sos-access#6]
When using latest marshmallow 3.4.0, sending alarms or ping will stop the program

>   File "C:\Program Files\Python36\lib\site-packages\marshmallow\schema.py", line 1224, in _invoke_processors
>     data = processor(data, many=many, **kwargs)
> TypeError: dump_xml() got an unexpected keyword argument 'many'

so i did a downgrade using 
`pip install "marshmallow==3.0.0b1"`
and now it works better

**Comment by Krolken** [comment]
Ah. I had stopped working actively with the library when the stable 3.x version was release. Thanks for spotting. Seems like it was an easy fix.

**Comment by jonasnic** [comment]
Nice 👍
