### ISSUE TITLE
Address format question

### ISSUE THREAD

**Issue by jonasnic** [pwitab/sos-access#7]
in client.py 
```
def connect(self, address=None):
        _address = address or self.address
        self.socket.connect(_address)
```
_adress = 'alarm.example.com'
( i'm just trying to get the code to run at this point som i'm just using the example text)

and i  receive
**Exception has occurred: TypeError
getsockaddrarg: AF_INET address must be tuple, not str**
  File "C:\Users\nojonic\Documents\PYTHON\SOS Alarm Access v4\sos_access\client.py", line 424, in connect
    self.socket.connect(_address)
  File "C:\Users\nojonic\Documents\PYTHON\SOS Alarm Access v4\sos_access\client.py", line 300, in transmit
    transport.connect()
...

I tried to simply do maket it a tuple with  port number = 0, but then it fails somewhere else.
```
def connect(self, address=None):
        _address = address or self.address
        self.socket.connect((_address,0))
```
 Exception has occurred: gaierror
[Errno 11001] getaddrinfo failed

I'm not sure if one is suppose to have an other socket.py or the code should accommodate tuple

OS : W10 
python 3.6
pip 20.0.2
marshmallow 3.0.0b1

**Comment by Krolken** [comment]
You need to provide proper address tuple. Using port 0 is not gonna work.
I have tested the library agains the test clients for SOS Alarm and Nokas/Avarn in Sweden.
Should look something like:
`address=('alarm.testserver.se', 1234)`

**Comment by jonasnic** [comment]
yeah, figured that out on my way home. the reason i had that other error message "[Errno 11001] getaddrinfo failed" was because it can't get the address info from a address that does not exist 'alarm.testserver.se'.
But using an address that exists actually helped..   

according to socket.py 
using port=0 will make it use "default" port number; whatever that is.

created pull req on updated  example where the receiving address includes port 


Thanks :)

**Comment by Krolken** [comment]
Merged your pull request. Closing the issue. Thanks again.
